name = "cloudfare-salary-tracker"
compatibility_date = "2026-05-23"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "salary-cycle-tracker-db"
database_id = "bce8ea8e-589d-4575-9709-5f5a8b1acdb5"
